//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuotationSystem2.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuotationSystem2.Resources.Language.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 此帳號已被使用，請使用其他帳號。 的當地語系化字串。
        /// </summary>
        internal static string AccountDuplicatedMessage {
            get {
                return ResourceManager.GetString("AccountDuplicatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開啟應用程式時發生錯誤，請聯絡開發人員。 的當地語系化字串。
        /// </summary>
        internal static string ApplicationStartErrorMessage {
            get {
                return ResourceManager.GetString("ApplicationStartErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法刪除自己的帳號，請重新選取。 的當地語系化字串。
        /// </summary>
        internal static string CannotDeleteOneselfMessage {
            get {
                return ResourceManager.GetString("CannotDeleteOneselfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 成功更改密碼。 的當地語系化字串。
        /// </summary>
        internal static string ChangePasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼預設為 的當地語系化字串。
        /// </summary>
        internal static string DefaultPasswordMessage {
            get {
                return ResourceManager.GetString("DefaultPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入所有必填欄位。 的當地語系化字串。
        /// </summary>
        internal static string FillInAllRequiredFieldsMessage {
            get {
                return ResourceManager.GetString("FillInAllRequiredFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入失敗，請確認帳號或密碼是否正確。 的當地語系化字串。
        /// </summary>
        internal static string LoginFailMessage {
            get {
                return ResourceManager.GetString("LoginFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先登入帳號。 的當地語系化字串。
        /// </summary>
        internal static string LoginRequiredMessage {
            get {
                return ResourceManager.GetString("LoginRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼須由大小寫英文字母或數字組成，且不超過15個字元 的當地語系化字串。
        /// </summary>
        internal static string PasswordConstraintMessage {
            get {
                return ResourceManager.GetString("PasswordConstraintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼格式不符合，請重新設定密碼。 的當地語系化字串。
        /// </summary>
        internal static string PasswordFormatInvalidMessage {
            get {
                return ResourceManager.GetString("PasswordFormatInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 舊密碼輸入錯誤，請重新輸入。 的當地語系化字串。
        /// </summary>
        internal static string PasswordIncorrectMessage {
            get {
                return ResourceManager.GetString("PasswordIncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇水管管徑。 的當地語系化字串。
        /// </summary>
        internal static string PipeDiameterEmptyMessage {
            get {
                return ResourceManager.GetString("PipeDiameterEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇至少一位使用者進行編輯。 的當地語系化字串。
        /// </summary>
        internal static string SelectOneUserMessage {
            get {
                return ResourceManager.GetString("SelectOneUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先選擇要刪除的使用者。 的當地語系化字串。
        /// </summary>
        internal static string SelectUserMessage {
            get {
                return ResourceManager.GetString("SelectUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者清單更新失敗。 的當地語系化字串。
        /// </summary>
        internal static string SetUserListFailMessage {
            get {
                return ResourceManager.GetString("SetUserListFailMessage", resourceCulture);
            }
        }
    }
}
